apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-cluster
  region: eu-west-2
  version: "1.22"

nodeGroups:
  - name: test-node-group
    instanceType: t2.medium
    desiredCapacity: 2
    volumeSize: 80
    privateNetworking: true
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
