apiVersion: v1
kind: Pod
metadata:
  name: nginx-new
  labels:
    job-key: myjob
spec:
  shareProcessNamespace: true
  containers:
  - name: nginx
    image: nginx
  - name: shell
    image: busybox:1.28
    securityContext:
      capabilities:
        add:
        - SYS_PTRACE
    stdin: true
    tty: true
